name: Build and Test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirement.txt

    - name: Give execute permission to bgmi
      run: chmod +x bgmi

    - name: Run m.py
      run: python m.py
